apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
spec:
  type: NodePort
  ports:
    - port: 30010
      targetPort: 9090
      nodePort: 30020
      name: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus

