apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmg-nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /apps/prometheusnfsfolderlogs/alertmanager
    server: 10.192.148.20
    readOnly: false

